### ISSUE TITLE
Photo posts triggering "content not found" error

### ISSUE THREAD

**Issue by jkk** [pocesar/actor-facebook-scraper#30]
Photo posts don't have an `og:url` meta tag and are getting marked as a not-found page here:

https://github.com/pocesar/actor-facebook-scraper/blob/master/src/main.ts#L422

Example run scraping https://www.facebook.com/GUCCI:

```
2020-12-29T14:41:42.476Z ACTOR: Creating Docker container.
2020-12-29T14:41:42.774Z ACTOR: Starting Docker container.
2020-12-29T14:41:46.364Z INFO  System info {"apifyVersion":"0.21.9","apifyClientVersion":"0.6.0","osType":"Linux","nodeVersion":"v12.18.4"}
2020-12-29T14:41:46.467Z INFO  Will use 649s timeout for page
2020-12-29T14:41:46.558Z INFO  Starting crawler with 1 urls
2020-12-29T14:41:46.560Z INFO  Using language "English (US)" (en-US)
2020-12-29T14:41:49.051Z INFO  PuppeteerCrawler:AutoscaledPool: state {"currentConcurrency":0,"desiredConcurrency":2,"systemStatus":{"isSystemIdle":true,"memInfo":{"isOverloaded":false,"limitRatio":0.2,"actualRatio":null},"eventLoopInfo":{"isOverloaded":false,"limitRatio":0.4,"actualRatio":null},"cpuInfo":{"isOverloaded":false,"limitRatio":0.4,"actualRatio":null},"clientInfo":{"isOverloaded":false,"limitRatio":0.3,"actualRatio":null}}}
2020-12-29T14:41:49.195Z INFO  Launching Puppeteer {"args":["--disable-setuid-sandbox","--no-sandbox"],"timeout":15000,"devtools":false,"useChrome":true,"stealth":false,"headless":false,"executablePath":"/usr/bin/google-chrome","defaultViewport":{"width":1366,"height":768},"proxyUrl":"http://session-session_nK56cYYjhQ:<redacted>@10.0.34.22:8011/"}
2020-12-29T14:42:25.746Z INFO  Stopping getting posts {"olderCount":0,"size":12,"threshold":9}
2020-12-29T14:42:25.748Z INFO  Got 12 posts in 4.747s {"username":"GUCCI","url":"https://www.facebook.com/pg/GUCCI/posts/"}
2020-12-29T14:42:35.305Z WARN  Content not found. This either means the page doesn't exist, or the section itself doesn't exist (about, reviews, services) {"runId":"7Os57unGwSE5TQyPn","time":"2020-12-29T14:42:35.303Z","meta":{"url":"https://www.facebook.com/GUCCI/photos/a.81172311012/10158674975081013/?type=3&__tn__=-R","namespace":"isNotFoundPage","userData":{"label":"POST","useMobile":false,"username":"GUCCI","canonical":"https://www.facebook.com/GUCCI/photos/a.81172311012/10158674975081013/","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36"}}}
2020-12-29T14:42:35.618Z ERROR handleFailedRequestFunction {"runId":"7Os57unGwSE5TQyPn","time":"2020-12-29T14:42:35.303Z","meta":{"url":"https://www.facebook.com/GUCCI/photos/a.81172311012/10158674975081013/?type=3&__tn__=-R","namespace":"isNotFoundPage","userData":{"label":"POST","useMobile":false,"username":"GUCCI","canonical":"https://www.facebook.com/GUCCI/photos/a.81172311012/10158674975081013/","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36"}}}
2020-12-29T14:42:35.620Z   InfoError: Content not found. This either means the page doesn't exist, or the section itself doesn't exist (about, reviews, services)
2020-12-29T14:42:35.622Z       at PuppeteerCrawler.handlePageFunction (/home/myuser/src/main.ts:427:27)
2020-12-29T14:42:35.624Z       at runMicrotasks (<anonymous>)
2020-12-29T14:42:35.626Z       at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-12-29T14:42:35.627Z       at /home/myuser/node_modules/apify/build/utils.js:362:26
2020-12-29T14:42:46.366Z INFO  Persisting to STATE.json...
2020-12-29T14:42:48.381Z INFO  Got 8 comments in 4.887s {"url":"https://www.facebook.com/GUCCI/posts/10158674975716013"}
2020-12-29T14:42:48.383Z INFO  Processed post in 4.995s {"url":"https://www.facebook.com/GUCCI/posts/10158674975716013"}
2020-12-29T14:42:49.178Z INFO  PuppeteerCrawler:AutoscaledPool: state {"currentConcurrency":1,"desiredConcurrency":1,"systemStatus":{"isSystemIdle":false,"memInfo":{"isOverloaded":false,"limitRatio":0.2,"actualRatio":0},"eventLoopInfo":{"isOverloaded":false,"limitRatio":0.4,"actualRatio":0.039},"cpuInfo":{"isOverloaded":true,"limitRatio":0.4,"actualRatio":0.648},"clientInfo":{"isOverloaded":false,"limitRatio":0.3,"actualRatio":0}}}
2020-12-29T14:42:49.298Z INFO  Statistics: PuppeteerCrawler request statistics: {"requestAvgFailedDurationMillis":9626,"requestAvgFinishedDurationMillis":27116,"requestsFinishedPerMinute":2,"requestsFailedPerMinute":0,"requestTotalDurationMillis":63858,"requestsTotal":3,"crawlerRuntimeMillis":60311,"retryHistogram":[3]}
2020-12-29T14:43:00.184Z WARN  Content not found. This either means the page doesn't exist, or the section itself doesn't exist (about, reviews, services) {"runId":"7Os57unGwSE5TQyPn","time":"2020-12-29T14:43:00.182Z","meta":{"url":"https://www.facebook.com/GUCCI/photos/a.81172311012/10158674973731013/?type=3&__tn__=-R","namespace":"isNotFoundPage","userData":{"label":"POST","useMobile":false,"username":"GUCCI","canonical":"https://www.facebook.com/GUCCI/photos/a.81172311012/10158674973731013/","userAgent":"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36"}}}
2020-12-29T14:43:00.310Z ERROR handleFailedRequestFunction {"runId":"7Os57unGwSE5TQyPn","time":"2020-12-29T14:43:00.182Z","meta":{"url":"https://www.facebook.com/GUCCI/photos/a.81172311012/10158674973731013/?type=3&__tn__=-R","namespace":"isNotFoundPage","userData":{"label":"POST","useMobile":false,"username":"GUCCI","canonical":"https://www.facebook.com/GUCCI/photos/a.81172311012/10158674973731013/","userAgent":"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36"}}}
2020-12-29T14:43:00.312Z   InfoError: Content not found. This either means the page doesn't exist, or the section itself doesn't exist (about, reviews, services)
2020-12-29T14:43:00.313Z       at PuppeteerCrawler.handlePageFunction (/home/myuser/src/main.ts:427:27)
2020-12-29T14:43:00.315Z       at runMicrotasks (<anonymous>)
2020-12-29T14:43:00.317Z       at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-12-29T14:43:00.318Z       at /home/myuser/node_modules/apify/build/utils.js:362:26
2020-12-29T14:43:12.575Z INFO  Got 9 comments in 4.972s {"url":"https://www.facebook.com/GUCCI/posts/10158674974611013"}
2020-12-29T14:43:12.577Z INFO  Processed post in 4.988s {"url":"https://www.facebook.com/GUCCI/posts/10158674974611013"}
2020-12-29T14:43:21.291Z WARN  Content not found. This either means the page doesn't exist, or the section itself doesn't exist (about, reviews, services) {"runId":"7Os57unGwSE5TQyPn","time":"2020-12-29T14:43:21.290Z","meta":{"url":"https://www.facebook.com/GUCCI/photos/a.81172311012/10158674972731013/?type=3&__tn__=-R","namespace":"isNotFoundPage","userData":{"label":"POST","useMobile":false,"username":"GUCCI","canonical":"https://www.facebook.com/GUCCI/photos/a.81172311012/10158674972731013/","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36"}}}
2020-12-29T14:43:21.672Z ERROR handleFailedRequestFunction {"runId":"7Os57unGwSE5TQyPn","time":"2020-12-29T14:43:21.290Z","meta":{"url":"https://www.facebook.com/GUCCI/photos/a.81172311012/10158674972731013/?type=3&__tn__=-R","namespace":"isNotFoundPage","userData":{"label":"POST","useMobile":false,"username":"GUCCI","canonical":"https://www.facebook.com/GUCCI/photos/a.81172311012/10158674972731013/","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36"}}}
2020-12-29T14:43:21.674Z   InfoError: Content not found. This either means the page doesn't exist, or the section itself doesn't exist (about, reviews, services)
2020-12-29T14:43:21.676Z       at PuppeteerCrawler.handlePageFunction (/home/myuser/src/main.ts:427:27)
2020-12-29T14:43:21.678Z       at runMicrotasks (<anonymous>)
2020-12-29T14:43:21.680Z       at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-12-29T14:43:21.681Z       at /home/myuser/node_modules/apify/build/utils.js:362:26

2020-12-29T14:43:46.366Z INFO  Persisting to STATE.json...
2020-12-29T14:43:49.185Z INFO  PuppeteerCrawler:AutoscaledPool: state {"currentConcurrency":1,"desiredConcurrency":1,"systemStatus":{"isSystemIdle":false,"memInfo":{"isOverloaded":false,"limitRatio":0.2,"actualRatio":0},"eventLoopInfo":{"isOverloaded":false,"limitRatio":0.4,"actualRatio":0},"cpuInfo":{"isOverloaded":true,"limitRatio":0.4,"actualRatio":0.564},"clientInfo":{"isOverloaded":false,"limitRatio":0.3,"actualRatio":0}}}
2020-12-29T14:43:49.298Z INFO  Statistics: PuppeteerCrawler request statistics: {"requestAvgFailedDurationMillis":9557,"requestAvgFinishedDurationMillis":20240,"requestsFinishedPerMinute":2,"requestsFailedPerMinute":1,"requestTotalDurationMillis":109630,"requestsTotal":7,"crawlerRuntimeMillis":120311,"retryHistogram":[7]}
2020-12-29T14:44:04.198Z WARN  Loading of new comments aborted {"url":"https://www.facebook.com/GUCCI/posts/10158674973331013"}
2020-12-29T14:44:04.202Z INFO  Got 2 comments in 36.588s {"url":"https://www.facebook.com/GUCCI/posts/10158674973331013"}
2020-12-29T14:44:04.205Z INFO  Processed post in 36.613s {"url":"https://www.facebook.com/GUCCI/posts/10158674973331013"}
2020-12-29T14:44:13.312Z WARN  Content not found. This either means the page doesn't exist, or the section itself doesn't exist (about, reviews, services) {"runId":"7Os57unGwSE5TQyPn","time":"2020-12-29T14:44:13.310Z","meta":{"url":"https://www.facebook.com/GUCCI/photos/a.81172311012/10158674971071013/?type=3&__tn__=-R","namespace":"isNotFoundPage","userData":{"label":"POST","useMobile":false,"username":"GUCCI","canonical":"https://www.facebook.com/GUCCI/photos/a.81172311012/10158674971071013/","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.5 Safari/605.1.15"}}}
2020-12-29T14:44:13.357Z ERROR handleFailedRequestFunction {"runId":"7Os57unGwSE5TQyPn","time":"2020-12-29T14:44:13.310Z","meta":{"url":"https://www.facebook.com/GUCCI/photos/a.81172311012/10158674971071013/?type=3&__tn__=-R","namespace":"isNotFoundPage","userData":{"label":"POST","useMobile":false,"username":"GUCCI","canonical":"https://www.facebook.com/GUCCI/photos/a.81172311012/10158674971071013/","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.5 Safari/605.1.15"}}}
2020-12-29T14:44:13.359Z   InfoError: Content not found. This either means the page doesn't exist, or the section itself doesn't exist (about, reviews, services)
2020-12-29T14:44:13.361Z       at PuppeteerCrawler.handlePageFunction (/home/myuser/src/main.ts:427:27)
2020-12-29T14:44:13.362Z       at runMicrotasks (<anonymous>)
2020-12-29T14:44:13.364Z       at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-12-29T14:44:13.366Z       at /home/myuser/node_modules/apify/build/utils.js:362:26
2020-12-29T14:44:46.367Z INFO  Persisting to STATE.json...
2020-12-29T14:44:49.193Z INFO  PuppeteerCrawler:AutoscaledPool: state {"currentConcurrency":1,"desiredConcurrency":1,"systemStatus":{"isSystemIdle":false,"memInfo":{"isOverloaded":false,"limitRatio":0.2,"actualRatio":0},"eventLoopInfo":{"isOverloaded":false,"limitRatio":0.4,"actualRatio":0},"cpuInfo":{"isOverloaded":true,"limitRatio":0.4,"actualRatio":0.439},"clientInfo":{"isOverloaded":false,"limitRatio":0.3,"actualRatio":0}}}
2020-12-29T14:44:49.298Z INFO  Statistics: PuppeteerCrawler request statistics: {"requestAvgFailedDurationMillis":9410,"requestAvgFinishedDurationMillis":24717,"requestsFinishedPerMinute":2,"requestsFailedPerMinute":1,"requestTotalDurationMillis":161225,"requestsTotal":9,"crawlerRuntimeMillis":180311,"retryHistogram":[9]}
2020-12-29T14:44:51.810Z WARN  Loading of new comments aborted {"url":"https://www.facebook.com/GUCCI/posts/10158674971921013"}
2020-12-29T14:44:51.812Z INFO  Got 0 comments in 31.12s {"url":"https://www.facebook.com/GUCCI/posts/10158674971921013"}
2020-12-29T14:44:51.814Z INFO  Processed post in 31.211s {"url":"https://www.facebook.com/GUCCI/posts/10158674971921013"}
2020-12-29T14:45:34.678Z WARN  Loading of new comments aborted {"url":"https://www.facebook.com/GUCCI/videos/721681995447690/?__tn__=-R"}
2020-12-29T14:45:34.680Z INFO  Got 0 comments in 31.16s {"url":"https://www.facebook.com/GUCCI/videos/721681995447690/?__tn__=-R"}
2020-12-29T14:45:34.682Z INFO  Processed post in 31.176s {"url":"https://www.facebook.com/GUCCI/videos/721681995447690/?__tn__=-R"}
2020-12-29T14:45:46.368Z INFO  Persisting to STATE.json...
2020-12-29T14:45:49.296Z INFO  PuppeteerCrawler:AutoscaledPool: state {"currentConcurrency":2,"desiredConcurrency":1,"systemStatus":{"isSystemIdle":false,"memInfo":{"isOverloaded":false,"limitRatio":0.2,"actualRatio":0},"eventLoopInfo":{"isOverloaded":false,"limitRatio":0.4,"actualRatio":0.057},"cpuInfo":{"isOverloaded":true,"limitRatio":0.4,"actualRatio":0.44},"clientInfo":{"isOverloaded":false,"limitRatio":0.3,"actualRatio":0}}}
2020-12-29T14:45:49.298Z INFO  Statistics: PuppeteerCrawler request statistics: {"requestAvgFailedDurationMillis":9410,"requestAvgFinishedDurationMillis":29302,"requestsFinishedPerMinute":2,"requestsFailedPerMinute":0,"requestTotalDurationMillis":242749,"requestsTotal":11,"crawlerRuntimeMillis":240311,"retryHistogram":[11]}
2020-12-29T14:45:50.313Z WARN  Content not found. This either means the page doesn't exist, or the section itself doesn't exist (about, reviews, services) {"runId":"7Os57unGwSE5TQyPn","time":"2020-12-29T14:45:50.311Z","meta":{"url":"https://www.facebook.com/GUCCI/photos/a.81172311012/10158674965096013/?type=3&__tn__=-R","namespace":"isNotFoundPage","userData":{"label":"POST","useMobile":false,"username":"GUCCI","canonical":"https://www.facebook.com/GUCCI/photos/a.81172311012/10158674965096013/","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.2 Safari/605.1.15"}}}
2020-12-29T14:45:50.434Z ERROR handleFailedRequestFunction {"runId":"7Os57unGwSE5TQyPn","time":"2020-12-29T14:45:50.311Z","meta":{"url":"https://www.facebook.com/GUCCI/photos/a.81172311012/10158674965096013/?type=3&__tn__=-R","namespace":"isNotFoundPage","userData":{"label":"POST","useMobile":false,"username":"GUCCI","canonical":"https://www.facebook.com/GUCCI/photos/a.81172311012/10158674965096013/","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.2 Safari/605.1.15"}}}
2020-12-29T14:45:50.436Z   InfoError: Content not found. This either means the page doesn't exist, or the section itself doesn't exist (about, reviews, services)
2020-12-29T14:45:50.438Z       at PuppeteerCrawler.handlePageFunction (/home/myuser/src/main.ts:427:27)
2020-12-29T14:45:50.440Z       at runMicrotasks (<anonymous>)
2020-12-29T14:45:50.441Z       at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-12-29T14:45:50.443Z       at /home/myuser/node_modules/apify/build/utils.js:362:26
2020-12-29T14:46:17.195Z WARN  Loading of new comments aborted {"url":"https://www.facebook.com/GUCCI/posts/10158674970766013"}
2020-12-29T14:46:17.197Z INFO  Got 0 comments in 31.599s {"url":"https://www.facebook.com/GUCCI/posts/10158674970766013"}
2020-12-29T14:46:17.199Z INFO  Processed post in 31.71s {"url":"https://www.facebook.com/GUCCI/posts/10158674970766013"}
2020-12-29T14:46:46.368Z INFO  Persisting to STATE.json...
2020-12-29T14:46:49.299Z INFO  Statistics: PuppeteerCrawler request statistics: {"requestAvgFailedDurationMillis":10614,"requestAvgFinishedDurationMillis":31621,"requestsFinishedPerMinute":2,"requestsFailedPerMinute":0,"requestTotalDurationMillis":306035,"requestsTotal":13,"crawlerRuntimeMillis":300312,"retryHistogram":[13]}
2020-12-29T14:46:49.394Z INFO  PuppeteerCrawler:AutoscaledPool: state {"currentConcurrency":1,"desiredConcurrency":3,"systemStatus":{"isSystemIdle":true,"memInfo":{"isOverloaded":false,"limitRatio":0.2,"actualRatio":0},"eventLoopInfo":{"isOverloaded":false,"limitRatio":0.4,"actualRatio":0},"cpuInfo":{"isOverloaded":false,"limitRatio":0.4,"actualRatio":0.368},"clientInfo":{"isOverloaded":false,"limitRatio":0.3,"actualRatio":0}}}
2020-12-29T14:46:56.788Z WARN  Loading of new comments aborted {"url":"https://www.facebook.com/GUCCI/posts/10158674967586013"}
2020-12-29T14:46:56.800Z INFO  Got 0 comments in 32.063s {"url":"https://www.facebook.com/GUCCI/posts/10158674967586013"}
2020-12-29T14:46:56.803Z INFO  Processed post in 32.088s {"url":"https://www.facebook.com/GUCCI/posts/10158674967586013"}
2020-12-29T14:46:57.123Z INFO  PuppeteerCrawler: All the requests from request list and/or request queue have been processed, the crawler will shut down.
2020-12-29T14:46:57.179Z INFO  PuppeteerCrawler: Final request statistics: {"requestAvgFailedDurationMillis":10614,"requestAvgFinishedDurationMillis":32481,"requestsFinishedPerMinute":2,"requestsFailedPerMinute":0,"requestTotalDurationMillis":345401,"requestsTotal":14,"crawlerRuntimeMillis":308192,"requestsFinished":9,"requestsFailed":5,"retryHistogram":[14]}
2020-12-29T14:46:57.775Z INFO  Persisting to STATE.json...
2020-12-29T14:46:57.878Z INFO  Generating dataset...
2020-12-29T14:46:57.939Z INFO  Done in 5m!

```

**Comment by pocesar** [comment]
thanks for the report @jkk Facebook is currently shifting layouts to the new one and it randomly fails depending if you hit the new format

**Comment by jkk** [comment]
@pocesar as far as I can tell, it appears to be failing for image posts 100% of the time. Most of the posts we need to scrape are image posts, which means the actor isn't really usable until this is addressed. Is a fix planned? Sorry to nag.

**Comment by pocesar** [comment]
@jkk it is planned, actually, got blocked by other throttling issues

**Comment by JackEPerry** [comment]
Just ran into this, is a fix still in the works? Thanks

**Comment by JackEPerry** [comment]
Hello, just ran into this error, is a fix still in the works?

Thanks!

**Comment by pocesar** [comment]
there's a workaround in place for this now. not sure how long it will last though
