### ISSUE TITLE
Feedback from testing

### ISSUE THREAD

**Issue by jancurn** [pocesar/actor-facebook-scraper#36]
Will add more over time.

Start urls => Start URLs

"Can provide either existing pages or business listing" ... sound strange, how about to say something like "Optional list of URLs of Facebook pages or business listings"

**Comment by jancurn** [comment]
I got this error when running with pretty much basic settings:

```
2021-04-13T08:37:08.859Z ERROR handleFailedRequestFunction {"runId":"3lvtFqy8yYokCHLVH","time":"2021-04-13T08:37:08.698Z","meta":{"url":"https://m.facebook.com/pg/ArmadaCeskerepubliky/reviews","namespace":"isNotFoundPage","userData":{"label":"PAGE","sub":"reviews","ref":"https://www.facebook.com/ArmadaCeskerepubliky","useMobile":true,"userAgent":"Mozilla/5.0 (Linux; Android 9; ONEPLUS A3003) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Mobile Safari/537.36"}}}
2021-04-13T08:37:08.860Z   InfoError: Content not found. This either means the page doesn't exist, or the section itself doesn't exist (about, reviews, services)
2021-04-13T08:37:08.861Z       at PuppeteerCrawler.handlePageFunction (/home/myuser/src/main.ts:477:27)
2021-04-13T08:37:08.861Z       at processTicksAndRejections (internal/process/task_queues.js:93:5)
2021-04-13T08:37:08.862Z       at PuppeteerCrawler._handleRequestFunction (/home/myuser/node_modules/apify/build/crawlers/browser_crawler.js:324:13)
2021-04-13T08:37:08.863Z       at PuppeteerCrawler._runTaskFunction (/home/myuser/node_modules/apify/build/crawlers/basic_crawler.js:423:13)
2021-04-13T08:37:08.864Z       at AutoscaledPool._maybeRunTask (/home/myuser/node_modules/apify/build/autoscaling/autoscaled_pool.js:388:13)
```

Is that expected? Perhaps it should be a warning then?

**Comment by pocesar** [comment]
@jancurn it is, Facebook is "brute force-y", you can only check if it exists by visiting the section (sometimes hidden from the tabs by admins). but this error in particular won't be re-tried, all errors are namespaced and only a few get retried

**Comment by jancurn** [comment]
Thanks for the explanation @pocesar. I'm just thinking that users might be a bit frightened by the "error"...
