### ISSUE TITLE
Posts not pulling in currently

### ISSUE THREAD

**Issue by JackEPerry** [pocesar/actor-facebook-scraper#37]
Hello,

We are receiving the following logs and empty output files when running this scraper

Anything we can do to prevent this? Thank you:

```2021-05-03T09:27:13.957Z WARN  Missing categories, most likely wrong mobile layout. This will be retried {"runId":"aKKUPbmM8gNNncaNl","time":"2021-05-03T09:27:13.954Z","meta":{"namespace":"getFieldInfos","url":"https://m.facebook.com/DeerValleyApartments/?refsrc=https%3A%2F%2Fm.facebook.com%2Fpg%2FDeerValleyApartments&_rdr"}}
2021-05-03T09:27:13.959Z ERROR PuppeteerCrawler: handleRequestFunction failed, reclaiming failed request back to the list or queue {"url":"https://m.facebook.com/pg/DeerValleyApartments?","retryCount":3,"id":"KNpMwopJVXyX9AW"}
2021-05-03T09:27:13.959Z   InfoError: Missing categories, most likely wrong mobile layout. This will be retried
2021-05-03T09:27:13.960Z       at Object.getFieldInfos (/home/myuser/src/page.ts:575:15)
2021-05-03T09:27:13.961Z       at runMicrotasks (<anonymous>)
2021-05-03T09:27:13.962Z       at processTicksAndRejections (internal/process/task_queues.js:93:5)
2021-05-03T09:27:13.962Z       at Object.append (/home/myuser/node_modules/async-atomic-store/src/index.ts:65:23)
2021-05-03T09:27:13.964Z       at PuppeteerCrawler.handlePageFunction (/home/myuser/src/main.ts:514:29)
2021-05-03T09:27:13.965Z       at PuppeteerCrawler._handleRequestFunction (/home/myuser/node_modules/apify/build/crawlers/browser_crawler.js:324:13)
2021-05-03T09:27:13.966Z       at PuppeteerCrawler._runTaskFunction (/home/myuser/node_modules/apify/build/crawlers/basic_crawler.js:423:13)
2021-05-03T09:27:13.967Z       at AutoscaledPool._maybeRunTask (/home/myuser/node_modules/apify/build/autoscaling/autoscaled_pool.js:388:13)

2021-05-03T09:27:22.824Z WARN  posts page selector not found {"runId":"aKKUPbmM8gNNncaNl","time":"2021-05-03T09:27:22.823Z","meta":{"namespace":"posts","selector":"abbr[data-utime]","url":"https://www.facebook.com/pg/DeerValleyApartments/posts/"}}
2021-05-03T09:27:22.831Z ERROR PuppeteerCrawler: handleRequestFunction failed, reclaiming failed request back to the list or queue {"url":"https://www.facebook.com/pg/DeerValleyApartments/posts?","retryCount":2,"id":"uxU3XETm2G2jYtg"}
2021-05-03T09:27:22.834Z   InfoError: posts page selector not found
2021-05-03T09:27:22.834Z       at Object.posts (/home/myuser/src/functions.ts:267:23)
2021-05-03T09:27:22.834Z       at getPosts (/home/myuser/src/page.ts:208:27)
2021-05-03T09:27:22.835Z       at maybeStop (/home/myuser/src/page.ts:316:21)
2021-05-03T09:27:22.835Z       at shouldContinue (/home/myuser/src/functions.ts:761:26)
2021-05-03T09:27:22.836Z       at Object.scrollUntil (/home/myuser/src/functions.ts:835:18)
2021-05-03T09:27:22.836Z       at Object.run (/home/myuser/node_modules/delayable-idle-abort-promise/src/index.ts:38:16)
2021-05-03T09:27:22.836Z       at Object.getPostUrls (/home/myuser/src/page.ts:311:9)
2021-05-03T09:27:22.837Z       at PuppeteerCrawler.handlePageFunction (/home/myuser/src/main.ts:571:47)
2021-05-03T09:27:22.837Z       at PuppeteerCrawler._handleRequestFunction (/home/myuser/node_modules/apify/build/crawlers/browser_crawler.js:324:13)
2021-05-03T09:27:22.837Z       at PuppeteerCrawler._runTaskFunction (/home/myuser/node_modules/apify/build/crawlers/basic_crawler.js:423:13)```

**Comment by pocesar** [comment]
hi @JackEPerry thanks for the report, it's being looked

**Comment by JackEPerry** [comment]
I think you fixed it Pocesar, thank you!
